### ISSUE TITLE
멘토링 전 최소 기능 구현

### ISSUE THREAD

**Issue by jhan117** [jhan117/Pebble-Pal#5]
- 권기영: Chat 기능
- 배창현: 블루투스 연결
- 신주아: 아두이노 회로 제작

**Comment by jua05** [comment]
- 권기영 : main화면 구현
- 배창현 : 블루투스 화면 구현, 연결
- 신주아 : led 센서 구현

**Comment by jhan117** [comment]
## 블루투스와 ESP32 관련해서 찾은 자료 공유

- [ESP32 시뮬레이터 사이트](https://wokwi.com/)
    - [vs code Extension](https://docs.wokwi.com/vscode/getting-started) 으로도 지원한다고 함
    - 장점: 조립하는 데 적은 시간이 들며 미리 설계도를 그릴 수 있고 공유 쉽게 가능 디버깅도 쉬움
    - 플러터 앱이랑도 웹에서 연결이 가능한데 AVD는 블루투스 기능을 제공하지 않아서 안드로이드 폰이 있어야 함
    - 일단 난 안드 폰 없음... => 폰이 없는 나는 기기로 받고 나머지는 폰으로 시뮬레이터로 하는 게 효율적일듯
- [블루투스 classic vs ble 공부 자료](https://www.mokosmart.com/ko/bluetooth-vs-bluetooth-low-energy-a-detailed-comparison/)
- [Getting Started with ESP32 Bluetooth Low Energy (BLE)](https://randomnerdtutorials.com/esp32-bluetooth-low-energy-ble-arduino-ide/)
    - 누가 한국어로 고대로 베껴온 걸 발견함 [한국어 블로그](https://blog.naver.com/heennavi1004/222170055404)
