### ISSUE TITLE
2024년 10월 9일 회의록

### ISSUE THREAD

**Issue by jua05** [jhan117/Pebble-Pal#7]

**Comment by jua05** [comment]
#6 멘토링 데이 후 피드백 하는 날!

**Comment by jhan117** [comment]
완료사항
- 신주아: 충격센서와 led 연결
- 권기영: main화면과 light 화면 구현
- 배창현: 블루투스 화면 구현

문제점
- 블루투스 연결은 됐지만 flutter의 패키지가 블루투스 classic을 지원하지 않음.
- 블루투스 기기를 앱 내부에서 연결하면 오류가 생길 가능성이 큼.

할 일
- 신주아: ble 이용한 코드로 변경
- 권기영: 블루투스 화면 변경하면서 블루투스 연결 로직 변경
